### ISSUE TITLE
Network error loading Relationships tab

### ISSUE THREAD

**Issue by Stoob** [twomice/com.joineryhq.relationshipjobtitle#1]
After a recent upgrade from 5.13 to 5.19, the Relationships tab will not load at all, with a 

> Network Error

black popup box in Civi.  Disabling this extension eliminates the error.  No other debugging seemed to be available.

**Comment by twomice** [comment]
Issue is fixed in 299db3d. Cutting a new version momentarily.

**Comment by twomice** [comment]
This fix is contained in master (of course) and in version tag 2.2. Should soon be available as a new version at https://civicrm.org/extensions/relationship-job-title
